export const CountryAbbreviation: { [s: string]: string } = {
    "Türkei": "tr",
    "Italien": "it",
    "Wales": "gb-wls",
    "Schweiz": "ch",
    "Schweden": "se",
    "Finnland": "fi",
    "Deutschland": "de",
    "England": "gb-eng",
    "Dänemark": "dk",
    "Russland": "ru",
    "Österreich": "at",
    "Belgien": "be",
    "Kroatien": "hr",
    "Nordmazedonien": "mk",
    "Niederlande": "nl",
    "Ukraine": "ua",
    "Spanien": "es",
    "Schottland": "gb-sct",
    "Tschechien": "cz",
    "Polen": "pl",
    "Slowakei": "sk",
    "Portugal": "pt",
    "Ungarn": "hu",
    "Frankreich": "fr",
    "Katar": "qa",
    "Ecuador": "ec",
    "Iran": "ir",
    "Senegal": "sn",
    "USA" : "us",
    "Argentinien" : "ar",
    "Saudi Arabien" : "sa",
    "Tunesien": "tn",
    "Mexiko": "mx",
    "Australien": "au",
    "Marokko": "ma",
    "Japan": "jp",
    "Costa Rica": "cr",
    "Kanada" : "ca",
    "Uruguay" : "uy",
    "Ghana" : "gh",
    "Brasilien" : "br",
    "Republik Korea" : "kr",
    "Kamerun": "cm",
    "Serbien" : "rs"
};